# Generated by Django 2.1.7 on 2023-07-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='nonameuser', max_length=10, unique=True, verbose_name='사용자 아이디')),
                ('user_name', models.CharField(max_length=10, unique=True, verbose_name='이름')),
                ('password', models.CharField(max_length=120, verbose_name='비밀번호')),
                ('user_birth', models.DateField(max_length=120, verbose_name='생년월일')),
                ('phonenumber', models.CharField(max_length=120, verbose_name='전화번호')),
                ('profile_image', models.ImageField(upload_to='profile_images/')),
                ('registered_dttm', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
            ],
        ),
    ]
