# Generated by Django 4.2.3 on 2023-07-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_id",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="사용자 아이디"
                    ),
                ),
                ("user_name", models.CharField(max_length=10, verbose_name="이름")),
                ("password", models.CharField(max_length=15, verbose_name="비밀번호")),
                ("user_birth", models.DateField(blank=True, verbose_name="생년월일")),
                (
                    "phonenumber",
                    models.CharField(blank=True, max_length=15, verbose_name="전화번호"),
                ),
                (
                    "profile_image",
                    models.ImageField(blank=True, upload_to="profile_images/"),
                ),
                (
                    "registered_dttm",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록시간"),
                ),
            ],
            options={
                "db_table": "tb_user",
            },
        ),
    ]
