# Generated by Django 4.2.3 on 2023-07-13 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="phonenumber",
        ),
        migrations.RemoveField(
            model_name="user",
            name="user_birth",
        ),
    ]
