# Generated by Django 2.1.7 on 2023-07-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=120, verbose_name='전화번호'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_birth',
            field=models.DateField(blank=True, max_length=120, verbose_name='생년월일'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='tb_user',
        ),
    ]
