# Generated by Django 3.2.19 on 2023-07-20 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_phonenumber_remove_user_user_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_image',
        ),
    ]
