# Generated by Django 2.1.7 on 2023-07-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20230708_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=15, verbose_name='비밀번호'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=15, verbose_name='전화번호'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_birth',
            field=models.DateField(blank=True, verbose_name='생년월일'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=10, unique=True, verbose_name='사용자 아이디'),
        ),
    ]
