# Generated by Django 3.2.19 on 2023-07-21 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_favorite'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
