# Generated by Django 4.2.3 on 2023-07-18 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0004_remove_book_id_alter_book_book_isbn"),
        ("community", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="community",
            name="book",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="book.book",
                verbose_name="도서",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="community",
            name="meeting_date",
            field=models.DateField(default="2023-01-01", verbose_name="모임 날짜"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="community",
            name="meeting_place",
            field=models.CharField(default="", max_length=20, verbose_name="모임 장소"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="community",
            name="status",
            field=models.CharField(
                choices=[("Y", "Yet"), ("C", "Current"), ("F", "Finished")],
                default="Y",
                max_length=10,
                verbose_name="모임 현황",
            ),
            preserve_default=False,
        ),
    ]
