# Generated by Django 4.2.3 on 2023-07-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0003_member"),
    ]

    operations = [
        migrations.AlterField(
            model_name="community",
            name="meeting_date",
            field=models.DateTimeField(verbose_name="모임 날짜"),
        ),
    ]
