# Generated by Django 4.2.3 on 2023-07-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0004_alter_community_meeting_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="community",
            name="status",
        ),
        migrations.AddField(
            model_name="community",
            name="description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="community",
            name="is_finished",
            field=models.BooleanField(default=False),
        ),
    ]
