# Generated by Django 4.2.3 on 2023-07-19 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0005_remove_community_status_community_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="Communityid",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="community.community",
            ),
            preserve_default=False,
        ),
    ]
