# Generated by Django 4.2.3 on 2023-07-19 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_remove_user_phonenumber_remove_user_user_birth"),
        ("community", "0006_member_communityid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="is_leader",
        ),
        migrations.AddField(
            model_name="community",
            name="creator",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="user.user",
                verbose_name="작성자",
            ),
            preserve_default=False,
        ),
    ]
