# Generated by Django 3.2.19 on 2023-07-20 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_remove_member_is_leader_community_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='Communityid',
            new_name='community',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='user_pk',
            new_name='user',
        ),
    ]
