# Generated by Django 4.2.3 on 2023-07-18 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("book_isbn", models.IntegerField(unique=True, verbose_name="ISBN")),
                ("book_title", models.CharField(max_length=20, verbose_name="도서명")),
                ("book_author", models.CharField(max_length=20, verbose_name="저자")),
                ("book_publisher", models.CharField(max_length=20, verbose_name="출판사")),
                ("book_page", models.IntegerField(verbose_name="페이지 수")),
                (
                    "book_description",
                    models.CharField(max_length=1000, verbose_name="책소개"),
                ),
                ("book_cover", models.CharField(max_length=400, verbose_name="책표지")),
            ],
            options={
                "db_table": "tb_book",
            },
        ),
    ]
