# Generated by Django 4.2.3 on 2023-07-18 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0003_alter_book_book_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="id",
        ),
        migrations.AlterField(
            model_name="book",
            name="book_isbn",
            field=models.IntegerField(
                primary_key=True, serialize=False, unique=True, verbose_name="ISBN"
            ),
        ),
    ]
