# Generated by Django 3.2.19 on 2023-07-20 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20230720_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_isbn',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ISBN'),
        ),
    ]
