# Generated by Django 3.2.19 on 2023-07-20 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_alter_book_book_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_page',
            field=models.IntegerField(default=0, verbose_name='페이지 수'),
            preserve_default=False,
        ),
    ]
