# Generated by Django 3.2.19 on 2023-07-20 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_category'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='tb_category',
        ),
    ]
