# Generated by Django 3.2.19 on 2023-07-20 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_alter_category_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_publisher',
        ),
    ]
